# .streamlit/secrets.toml

[api_keys]
"Giáo viên A" = "AIzaSyBUOw6NBOf6YQcWcRtz5LKDdGqyVch0fIo"
"Giáo viên B" = "YOUR_API_KEY_B_HERE"
"Default" = "AIzaSyBUOw6NBOf6YQcWcRtz5LKDdGqyVch0fIo" # Giữ lại key cũ của bạn
